# Generated by Django 6.0.3 on 2026-03-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_answer",
                    models.TextField(verbose_name="Yuborilgan javob/kod"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="To'g'rimi?"),
                ),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ushbu urinish uchun AI xulosasi",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Bajarildi"),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Bal")),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="Eng so'nggi AI xulosasi"
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lessons.task",
                        verbose_name="Topshiriq",
                    ),
                ),
            ],
        ),
    ]
