# Generated by Django 6.0.3 on 2026-03-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FIRST_STEP", "🏁 Birinchi qadam"),
                            ("ON_FIRE", "🔥 Olovli o'rganuvchi"),
                            ("QUICK_THINKER", "⚡ Tez fikrlovchi"),
                            ("COURSE_COMPLETE", "🎓 Kurs tamomladi"),
                            ("TOP_LEARNER", "🏆 Top o'rganuvchi"),
                            ("XP_100", "💯 100 XP yig'di"),
                            ("XP_500", "🌟 500 XP yig'di"),
                            ("XP_1000", "🚀 Expert darajasi"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("description", models.TextField(verbose_name="Tavsifi")),
                (
                    "icon",
                    models.CharField(
                        default="🏅", max_length=10, verbose_name="Ikon (emoji)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badge lar",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0, verbose_name="XP ball")),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Daraja"),
                ),
                (
                    "level_name",
                    models.CharField(
                        default="Yangi boshlovchi",
                        max_length=50,
                        verbose_name="Daraja nomi",
                    ),
                ),
                (
                    "streak_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ketma-ket kunlar"
                    ),
                ),
                (
                    "last_active_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Oxirgi faollik sanasi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Foydalanuvchi profili",
                "verbose_name_plural": "Foydalanuvchi profillari",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Olingan vaqti"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.badge",
                        verbose_name="Badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi Badge",
                "verbose_name_plural": "Foydalanuvchi Badge lari",
                "ordering": ["-earned_at"],
            },
        ),
    ]
