# Generated by Django 6.0.3 on 2026-03-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Dars mavzusi"),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Dars matni/izohi"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False, verbose_name="AI tomonidan yaratilganmi?"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="Darsga tegishli kurs",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Vazifa", max_length=255, verbose_name="Topshiriq nomi"
                    ),
                ),
                ("question", models.TextField(verbose_name="Topshiriq sharti")),
                (
                    "expected_output",
                    models.TextField(verbose_name="Kutilayotgan natija"),
                ),
                (
                    "ai_hints",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="AI orqali beriladigan yordam/hintlar",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="lessons.lesson",
                        verbose_name="Topshiriq darsi",
                    ),
                ),
            ],
        ),
    ]
