# Generated by Django 4.2.25 on 2026-04-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Test nomi")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Testlar",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["order"],
                "verbose_name": "Kod topshirig'i",
                "verbose_name_plural": "Kod topshiriqlari",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "🟢 Boshlang'ich"),
                    ("intermediate", "🟡 O'rta"),
                    ("advanced", "🔴 Ilg'or"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="Daraja",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Taxminiy o'qish (daqiqa)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("theory", "📘 Nazariy dars"),
                    ("video", "🎬 Video dars"),
                    ("mixed", "🔀 Video + Matn"),
                ],
                default="theory",
                max_length=20,
                verbose_name="Dars turi",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Qisqa tavsif"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lessons/videos/",
                verbose_name="Video fayl (upload)",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="YouTube video URL"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "🟢 Boshlang'ich"),
                    ("intermediate", "🟡 O'rta"),
                    ("advanced", "🔴 Ilg'or"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="Daraja",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Tartib raqami"),
        ),
        migrations.AddField(
            model_name="task",
            name="starter_code",
            field=models.TextField(
                blank=True, verbose_name="Boshlang'ich kod (foydalanuvchiga beriladi)"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True, verbose_name="Dars matni (HTML)"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
                verbose_name="Kursga tegishli",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="ai_hints",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI yordami / maslahat"
            ),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Savol matni")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "🔘 Ko'p tanlov (A/B/C/D)"),
                            ("true_false", "✅ To'g'ri / Noto'g'ri"),
                            ("code_output", "💻 Kod natijasini toping"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Savol turi",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="To'g'ri javob izohi"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lessons.quiz",
                        verbose_name="Testga tegishli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(
                        max_length=500, verbose_name="Javob varianti matni"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="To'g'ri javobmi?"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="lessons.quizquestion",
                        verbose_name="Savolga tegishli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Javob varianti",
                "verbose_name_plural": "Javob variantlari",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="lessons.lesson",
                verbose_name="Darsga tegishli",
            ),
        ),
    ]
